[package]
name = "mvc_core"
version = "0.2.0"
edition = "2024"
authors = []
[dependencies]
serde = {version = "1.0.228", features=["derive"]}
serde_json = "1.0.149"
tar = "0.4.44"
sha2 = "0.10"
walkdir = "2.5.0"
[lib]
name="mvc_core"
path="src/lib.rs"
